name: 'PHPUnit Problem Matcher'
description: 'Registers a problem matcher for PHPUnit'
author: 'decnorton'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: check-square
  color: purple
